# Generated by Django 4.1.7 on 2023-03-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
